<?xml version="1.0" encoding="UTF-8"?><!DOCTYPE article [
        <!ELEMENT article (front|body|back)*>
        <!ATTLIST article
                article-type CDATA #REQUIRED
                dtd-version CDATA #REQUIRED
                xml:lang CDATA #REQUIRED
                xmlns:xlink CDATA #REQUIRED>
        <!ELEMENT front (journal-meta|article-meta)*>
        <!ELEMENT journal-meta (journal-id|journal-title-group|issn|publisher)*>
        <!ELEMENT journal-id (#PCDATA)>
        <!ATTLIST journal-id
                journal-id-type CDATA #REQUIRED>
        <!ELEMENT journal-title-group (journal-title)*>
        <!ELEMENT journal-title (#PCDATA)>
        <!ELEMENT issn (#PCDATA)>
        <!ATTLIST issn
                pub-type CDATA #REQUIRED>
        <!ELEMENT publisher (publisher-name|publisher-loc)*>
        <!ELEMENT publisher-name (#PCDATA)>
        <!ELEMENT publisher-loc (#PCDATA)>
        <!ELEMENT article-meta (article-id|article-categories|title-group|contrib-group|aff|author-notes|pub-date|volume|issue|fpage|lpage|permissions|self-uri|abstract|kwd-group)*>
        <!ELEMENT article-id (#PCDATA)>
        <!ATTLIST article-id
                pub-id-type CDATA #REQUIRED>
        <!ELEMENT article-categories (subj-group)*>
        <!ELEMENT subj-group (subject)*>
        <!ATTLIST subj-group
                subj-group-type CDATA #REQUIRED>
        <!ELEMENT subject (#PCDATA)>
        <!ELEMENT title-group (article-title)*>
        <!ELEMENT article-title (#PCDATA)>
        <!ELEMENT contrib-group (contrib|x)*>
        <!ELEMENT contrib (string-name|x|degrees|xref)*>
        <!ATTLIST contrib
                contrib-type CDATA #REQUIRED>
        <!ELEMENT string-name (given-names|surname)*>
        <!ELEMENT given-names (#PCDATA)>
        <!ELEMENT surname (#PCDATA)>
        <!ELEMENT x (#PCDATA)>
        <!ELEMENT degrees (#PCDATA)>
        <!ELEMENT xref (sup|italic)*>
        <!ATTLIST xref
                ref-type CDATA #REQUIRED
                rid CDATA #REQUIRED>
        <!ELEMENT sup (#PCDATA)>
        <!ELEMENT aff (label)*>
        <!ATTLIST aff
                id CDATA #REQUIRED>
        <!ELEMENT label (sup)*>
        <!ELEMENT author-notes (corresp)*>
        <!ELEMENT corresp (email)*>
        <!ATTLIST corresp
                id CDATA #REQUIRED>
        <!ELEMENT email (#PCDATA)>
        <!ELEMENT pub-date (month|year)*>
        <!ATTLIST pub-date
                pub-type CDATA #REQUIRED>
        <!ELEMENT month (#PCDATA)>
        <!ELEMENT year (#PCDATA)>
        <!ELEMENT volume (#PCDATA)>
        <!ELEMENT issue (#PCDATA)>
        <!ELEMENT fpage (#PCDATA)>
        <!ELEMENT lpage (#PCDATA)>
        <!ELEMENT permissions (copyright-statement|copyright-year|copyright-holder)*>
        <!ELEMENT copyright-statement (#PCDATA)>
        <!ELEMENT copyright-year (#PCDATA)>
        <!ELEMENT copyright-holder (#PCDATA)>
        <!ATTLIST copyright-holder
                content-type CDATA #REQUIRED>
        <!ELEMENT self-uri (#PCDATA)>
        <!ATTLIST self-uri
                content-type CDATA #REQUIRED
                xlink:href CDATA #REQUIRED>
        <!ELEMENT abstract (p)*>
        <!ELEMENT p (italic|xref|bold)*>
        <!ELEMENT italic (#PCDATA)>
        <!ELEMENT kwd-group (kwd|x)*>
        <!ELEMENT kwd (#PCDATA)>
        <!ELEMENT body (p|sec)*>
        <!ELEMENT sec (title|p|table-wrap|sec|list|fig)*>
        <!ATTLIST sec
                id CDATA #REQUIRED
                sec-type CDATA #IMPLIED>
        <!ELEMENT title (#PCDATA)>
        <!ELEMENT table-wrap (label|caption|alternatives|table-wrap-foot)*>
        <!ATTLIST table-wrap
                id CDATA #REQUIRED
                position CDATA #REQUIRED>
        <!ELEMENT caption (p)*>
        <!ELEMENT alternatives (graphic|table)*>
        <!ELEMENT graphic (#PCDATA)>
        <!ATTLIST graphic
                xlink:href CDATA #REQUIRED>
        <!ELEMENT table (colgroup|thead|tbody)*>
        <!ELEMENT colgroup (col)*>
        <!ELEMENT col (#PCDATA)>
        <!ATTLIST col
                align CDATA #REQUIRED
                char CDATA #IMPLIED>
        <!ELEMENT thead (tr)*>
        <!ELEMENT tr (th|td)*>
        <!ELEMENT th (#PCDATA)>
        <!ATTLIST th
                align CDATA #REQUIRED>
        <!ELEMENT tbody (tr)*>
        <!ELEMENT td (#PCDATA)>
        <!ATTLIST td
                colspan CDATA #IMPLIED>
        <!ELEMENT list (list-item)*>
        <!ATTLIST list
                id CDATA #REQUIRED
                list-type CDATA #REQUIRED>
        <!ELEMENT list-item (p)*>
        <!ELEMENT bold (#PCDATA)>
        <!ELEMENT table-wrap-foot (fn)*>
        <!ELEMENT fn (p|label)*>
        <!ATTLIST fn
                fn-type CDATA #IMPLIED
                id CDATA #IMPLIED>
        <!ELEMENT fig (label|caption|graphic)*>
        <!ATTLIST fig
                id CDATA #REQUIRED
                position CDATA #REQUIRED>
        <!ELEMENT back (fn-group|ref-list)*>
        <!ELEMENT fn-group (fn)*>
        <!ELEMENT ref-list (title|ref)*>
        <!ELEMENT ref (mixed-citation)*>
        <!ATTLIST ref
                id CDATA #REQUIRED>
        <!ELEMENT mixed-citation (collab|year|source|publisher-loc|publisher-name|person-group|article-title|volume|fpage|lpage|pub-id|edition|ext-link)*>
        <!ATTLIST mixed-citation
                publication-type CDATA #REQUIRED>
        <!ELEMENT collab (#PCDATA)>
        <!ELEMENT source (#PCDATA)>
        <!ELEMENT person-group (string-name)*>
        <!ATTLIST person-group
                person-group-type CDATA #REQUIRED>
        <!ELEMENT pub-id (#PCDATA)>
        <!ATTLIST pub-id
                pub-id-type CDATA #REQUIRED>
        <!ELEMENT edition (#PCDATA)>
        <!ELEMENT ext-link (#PCDATA)>
        <!ATTLIST ext-link
                ext-link-type CDATA #REQUIRED
                xlink:href CDATA #REQUIRED>
        ]>
<article article-type="research-article" dtd-version="1.1d1" xml:lang="en" xmlns:xlink="http://www.w3.org/1999/xlink">
    <front>
        <journal-meta>
            <journal-id journal-id-type="publisher-id">BHDA</journal-id>
            <journal-id journal-id-type="sage">BHD</journal-id>
            <journal-title-group>
                <journal-title>Behavioral Disorders</journal-title>
            </journal-title-group>
            <issn pub-type="ppub">0198-7429</issn>
            <issn pub-type="epub">2163-5307</issn>
            <publisher>
                <publisher-name>SAGE Publications</publisher-name>
                <publisher-loc>Sage CA: Los Angeles, CA</publisher-loc>
            </publisher>
        </journal-meta>
        <article-meta>
            <article-id pub-id-type="doi">10.1177/0198742916688653</article-id>
            <article-id pub-id-type="publisher-id">10.1177_0198742916688653</article-id>
            <article-categories>
                <subj-group subj-group-type="heading">
                    <subject>Articles</subject>
                </subj-group>
            </article-categories>
            <title-group>
                <article-title>Quality Indicators for Systematic Reviews in Behavioral Disorders</article-title>
            </title-group>
            <contrib-group>
                <contrib contrib-type="author">
                    <string-name>
                        <given-names>Daniel M.</given-names>
                        <surname>Maggin</surname>
                    </string-name>
                    <x>,</x>
                    <degrees>PhD</degrees>
                    <xref ref-type="aff" rid="aff1-0198742916688653">
                        <sup>1</sup>
                    </xref>
                    <xref ref-type="corresp" rid="corresp1-0198742916688653"/>
                </contrib>
                <x>,</x>
                <contrib contrib-type="author">
                    <string-name>
                        <given-names>Elizabeth</given-names>
                        <surname>Talbott</surname>
                    </string-name>
                    <x>,</x>
                    <degrees>PhD</degrees>
                    <xref ref-type="aff" rid="aff1-0198742916688653">
                        <sup>1</sup>
                    </xref>
                </contrib>
                <x>,</x>
                <contrib contrib-type="author">
                    <string-name>
                        <given-names>Eryn Y.</given-names>
                        <surname>Van Acker</surname>
                    </string-name>
                    <x>,</x>
                    <degrees>MA</degrees>
                    <xref ref-type="aff" rid="aff1-0198742916688653">
                        <sup>1</sup>
                    </xref>
                </contrib>
                <x>,</x>
                <contrib contrib-type="author">
                    <string-name>
                        <given-names>Skip</given-names>
                        <surname>Kumm</surname>
                    </string-name>
                    <x>,</x>
                    <degrees>MA</degrees>
                    <xref ref-type="aff" rid="aff1-0198742916688653">
                        <sup>1</sup>
                    </xref>
                </contrib>
            </contrib-group>
            <aff id="aff1-0198742916688653">
                <label>
                    <sup>1</sup>
                </label>
                The University of Illinois at Chicago, USA
            </aff>
            <author-notes>
                <corresp id="corresp1-0198742916688653">Daniel M. Maggin, The University of Illinois at Chicago, 3424
                    ETMSW, 1040 W Harrison Street, Chicago, IL 60607, USA. Email:
                    <email>dmaggin@uic.edu</email>
                </corresp>
            </author-notes>
            <pub-date pub-type="epub-ppub">
                <month>2</month>
                <year>2017</year>
            </pub-date>
            <volume>42</volume>
            <issue>2</issue>
            <fpage>52</fpage>
            <lpage>64</lpage>
            <permissions>
                <copyright-statement>© Hammill Institute on Disabilities 2017</copyright-statement>
                <copyright-year>2017</copyright-year>
                <copyright-holder content-type="society">Hammill Institute on Disabilities. All rights reserved
                </copyright-holder>
            </permissions>
            <self-uri content-type="pdf" xlink:href="0198742916688653.pdf"/>
            <abstract>
                <p>Special education researchers, practitioners, and policy makers continue to work toward developing
                    and implementing empirically supported practices and policies to address the academic, social, and
                    postschool challenges confronting students with emotional and behavioral disorders. The systematic
                    review has become an essential vehicle for compiling and disseminating research findings on an array
                    of topics. Given the importance and impact of these research summaries, it is instructive to take
                    stock of the extent to which reviews in our field adhere to current standards. Drawing from a number
                    of sources in the social and behavioral sciences, we propose and describe a series of quality
                    indicators for systematic reviews. We applied these indicators to systematic reviews published in <italic>
                        Behavioral Disorders
                    </italic> between 2005 and 2016 with the broader goal of identifying areas of methodological
                    strength and areas for improvement. Results indicate that the sample of systematic reviews
                    demonstrated particular strength in several procedural domains such as the specification of
                    inclusion criteria, identifying the electronic databases used for the search, and describing the
                    plan for data analysis. We also identified a number of areas to which researchers might devote
                    greater attention to increase the rigor of systematic reviews in the field. Findings are
                    contextualized within the importance of research transparency and reporting to improve practice and
                    policy.
                </p>
            </abstract>
            <kwd-group>
                <kwd>emotional and behavioral disorders</kwd>
                <x>,</x>
                <kwd>quality indicators</kwd>
                <x>,</x>
                <kwd>meta-analysis</kwd>
                <x>,</x>
                <kwd>systematic review</kwd>
            </kwd-group>
        </article-meta>
    </front>
    <body>
        <p>The development, identification, and dissemination of evidence-based intervention and assessment strategies
            have been a dominant theme within education for more than a decade (<xref ref-type="bibr"
                                                                                      rid="bibr24-0198742916688653">
                Shavelson &amp; Towne, 2002</xref>). Following the logic of evidence-based practice, rigorous research
            methods are used to determine which strategies are most likely to produce the desired outcomes (<xref
                    ref-type="bibr" rid="bibr12-0198742916688653">Gersten et al., 2005</xref>). A critical aspect of the
            identification of evidence-based educational methods is to reliably summarize the research on a given topic
            to assess the methodological strength and consistency of findings to draw meaningful conclusions. As such,
            the systematic review has gained increased attention for its emphasis on providing transparent assessments
            of research (<xref ref-type="bibr" rid="bibr8-0198742916688653">Cook, Tankersley, &amp; Landrum, 2009</xref>).
            Given the variety of academic, social, and postschool challenges confronting students with emotional and
            behavioral disorders (EBD), systematic research reviews can have significant implications and reach for
            guiding the adoption and implementation of various educational practices and policies for this particularly
            vulnerable population of students. For instance, the results of systematic reviews can be used by
            practitioners to select intervention methods, policy makers to weigh the costs and benefits of adopting
            particular strategies, researchers to identify the strengths and weaknesses within a body of research to
            assist with planning their next study, grant funders to determine issues that are in need of additional
            attention and resources, and the developers of standards to detect promising strategies and practices (<xref
                    ref-type="bibr" rid="bibr25-0198742916688653">Talbott, Maggin, Van Acker, &amp; Kumm, in
                press</xref>). The strength of systematic reviews derives from the articulation of a clear, transparent,
            replicable methodology that increases the likelihood of drawing objective conclusions from the research
            being reviewed. As such, the systematic review has become an essential tool within the development and
            dissemination of empirically supported practices and policies for students with EBD (<xref ref-type="bibr"
                                                                                                       rid="bibr18-0198742916688653">
                Maggin &amp; Chafouleas, 2013</xref>).
        </p>
        <p>Despite the importance of systematic reviews for understanding and addressing an array of complex issues for
            students with EBD, field-specific guidance for researchers or practitioners on this research methodology is
            currently unavailable. The purpose of this article, therefore, is to follow the lead of previous efforts in
            the field to establish guidelines and provide an overview of common quality indicators for conducting
            systematic reviews (<xref ref-type="bibr" rid="bibr23-0198742916688653">Odom et al., 2005</xref>). In the
            following sections, we define systematic reviews in relation to other types of literature reviews, describe
            common quality indicators for systematic reviews, and provide a conceptual discussion of the reasons these
            standards are important. We then apply these indicators to systematic reviews published in <italic>
                Behavioral Disorders
            </italic> from 2005 to 2016 to identify areas of methodological strength and areas for improvement in recent
            reviews in the field. The article concludes with recommendations for improving the overall quality of
            systematic reviews in our discipline, to ensure that the most valid information is disseminated for students
            with EBD who have among the most unique and complex needs in special education (<xref ref-type="bibr"
                                                                                                  rid="bibr19-0198742916688653">
                Maggin, Wehby, Farmer, &amp; Brooks, 2016</xref>).
        </p>
        <sec id="section1-0198742916688653">
            <title>Defining Systematic Reviews</title>
            <p>A systematic review is the attempt to systematically collate all empirical evidence that meets a set of
                specific eligibility criteria with the purpose of answering a particular research question (<xref
                        ref-type="bibr" rid="bibr16-0198742916688653">Lipsey &amp; Wilson, 2001</xref>). As such, these
                research syntheses require the development of clearly articulated procedures that are selected to
                minimize subjectivity and maximize transparency, which increase the likelihood of providing reliable
                findings from which objective conclusions can be drawn to support decision making for policy and
                practice (<xref ref-type="bibr" rid="bibr3-0198742916688653">Borenstein, Hedges, Higgins, &amp;
                    Rothstein, 2009</xref>). It is essential not only to define systematic reviews but also to
                distinguish them from other types of literature reviews used in our field. For instance, systematic
                reviews are fundamentally different from narrative reviews and position papers in that researchers
                describe and use a replicable, transparent set of procedures to search, include, and review the research
                on a given topic. In contrast, narrative reviews typically do not provide details on how particular
                decisions are made regarding the relevance and consideration of the included studies (<xref
                        ref-type="bibr" rid="bibr2-0198742916688653">Baumeister &amp; Leary, 1997</xref>). This is not
                to discount the importance of narrative reviews; in fact, narrative reviews can often be a means for
                disseminating powerful scholarship and perspective. Another type of review that is common in our field,
                and one that is closely related to systematic reviews, is the meta-analysis. There is often confusion,
                however, regarding the differences between a meta-analysis and a systematic review. Meta-analysis refers
                explicitly to the use of statistical methods to summarize and combine the results of independent
                research studies (<xref ref-type="bibr" rid="bibr9-0198742916688653">Cooper, Hedges, &amp; Valentine,
                    2009</xref>). As such, a systematic review does not require the use of meta-analytic techniques
                although the validity of findings from a meta-analysis is directly related to the quality of the
                systematic review procedures used to reduce bias (<xref ref-type="bibr" rid="bibr16-0198742916688653">
                    Lipsey &amp; Wilson, 2001</xref>).
            </p>
        </sec>
        <sec id="section2-0198742916688653">
            <title>Guidelines for Systematic Reviews</title>
            <p>Part of the motivation for the current article is to provide researchers and research consumers with a
                set of guidelines to use when conducting and reviewing systematic reviews. These efforts are similar to
                the development of indicators for primary research proposed by our esteemed colleagues in special
                education more than a decade ago (<xref ref-type="bibr" rid="bibr23-0198742916688653">Odom et al.,
                    2005</xref>). The purpose of those methodological guidelines, as with those proffered here, was to
                encourage the use of strong research methods to ensure the most valid information is obtained and
                disseminated. It is important to note that the development of quality indicators has not been isolated
                to the execution of primary research studies in the field of special education. In fact, there have been
                several efforts to establish guidelines for conducting systematic reviews in other areas of the social
                and behavioral sciences (e.g., <xref ref-type="bibr" rid="bibr1-0198742916688653">American Psychological
                    Association [APA], 2010</xref>; <xref ref-type="bibr" rid="bibr14-0198742916688653">Higgins &amp;
                    Green, 2011</xref>; <xref ref-type="bibr" rid="bibr22-0198742916688653">Moher et al., 2015</xref>).
                These endeavors have led to the development of a set of widely accepted standards on the processes and
                procedures for conducting a rigorous systematic review. In the current article, we synthesize extant
                guidelines to generate a set of quality indicators for conducting and reporting rigorous systematic
                reviews in special education generally and in the field of EBD specifically.
            </p>
        </sec>
        <sec id="section3-0198742916688653">
            <title>Quality Indicators for Systematic Reviews</title>
            <p>In the following sections, we provide an overview of the quality indicators for conducting systematic
                reviews. Each criterion and its operational definition are presented in <xref ref-type="table"
                                                                                              rid="table1-0198742916688653">
                    Table 1</xref>.
            </p>
            <table-wrap id="table1-0198742916688653" position="float">
                <label>Table 1.</label>
                <caption>
                    <p>Methodological Quality Indicators for Conducting Systematic Reviews.</p>
                </caption>
                <alternatives>
                    <graphic xlink:href="10.1177_0198742916688653-table1.tif"/>
                    <table>
                        <colgroup>
                            <col align="left"/>
                            <col align="left"/>
                        </colgroup>
                        <thead>
                            <tr>
                                <th align="left">Methodological Domain</th>
                                <th align="left">Quality indicator</th>
                            </tr>
                        </thead>
                        <tbody>
                            <tr>
                                <td colspan="2">Research question</td>
                            </tr>
                            <tr>
                                <td> Research question formulation</td>
                                <td>The research question communicates the objectives and provides boundaries for making
                                    decisions about which studies to include in the systematic review.
                                </td>
                            </tr>
                            <tr>
                                <td colspan="2">Eligibility criteria</td>
                            </tr>
                            <tr>
                                <td> Variable characteristics</td>
                                <td>Operational characteristics of the variables that will be the focus of the review
                                    are described with examples of key variables such as the interventions, assessments,
                                    programs, practices, or policies of interest.
                                </td>
                            </tr>
                            <tr>
                                <td> Participant information</td>
                                <td>Key participant information is reported including any disability, demographic,
                                    and/or functional characteristics that define the student population.
                                </td>
                            </tr>
                            <tr>
                                <td> Research design</td>
                                <td>The research designs eligible for the review are identified with key methods
                                    operationalized if necessary.
                                </td>
                            </tr>
                            <tr>
                                <td> Time period</td>
                                <td>The time period in which the research had to be published to be eligible was
                                    identified.
                                </td>
                            </tr>
                            <tr>
                                <td colspan="2">Search procedures</td>
                            </tr>
                            <tr>
                                <td> Databases identified</td>
                                <td>The electronic reference databases searched were referenced directly.</td>
                            </tr>
                            <tr>
                                <td> Registries identified</td>
                                <td>The prospective research registries searched were referenced directly.</td>
                            </tr>
                            <tr>
                                <td> Unpublished sources</td>
                                <td>The authors reported whether unpublished studies were included in the search.</td>
                            </tr>
                            <tr>
                                <td> Keywords identified</td>
                                <td>Keywords used to search reference databases and registries were explicitly
                                    identified.
                                </td>
                            </tr>
                            <tr>
                                <td> Search date</td>
                                <td>The date on which the final search was conducted was reported.</td>
                            </tr>
                            <tr>
                                <td> Hand search conducted</td>
                                <td>The authors reported whether journals were hand searched and, if so, which
                                    journals.
                                </td>
                            </tr>
                            <tr>
                                <td> Citation lists review</td>
                                <td>The authors reported whether citation lists of included studies were reviewed and,
                                    if so, which studies.
                                </td>
                            </tr>
                            <tr>
                                <td> Subject matter expert review</td>
                                <td>The authors reported whether individuals with expertise on the subject matter of the
                                    review examined the citation list to assist with identifying additional, relevant
                                    studies.
                                </td>
                            </tr>
                            <tr>
                                <td> Review articles consulted</td>
                                <td>The authors reported whether pertinent review articles were reviewed for
                                    citations.
                                </td>
                            </tr>
                            <tr>
                                <td> Authors contacted</td>
                                <td>The authors reported whether authors were contacted to see if other reports were
                                    available.
                                </td>
                            </tr>
                            <tr>
                                <td> Language specification</td>
                                <td>The authors specified the languages of eligible reports and if there were any
                                    limitations imposed on the language of the report.
                                </td>
                            </tr>
                            <tr>
                                <td> Titles and abstracts reviewed</td>
                                <td>The authors reported whether titles and abstracts were used to determine eligibility
                                    in the study.
                                </td>
                            </tr>
                            <tr>
                                <td> Searcher qualification</td>
                                <td>The authors reported the qualifications for those reviewing studies for
                                    eligibility.
                                </td>